/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio1;

/**
 *
 * @author ivangq
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEste = new javax.swing.JPanel();
        pnlESur = new javax.swing.JPanel();
        pnlOeste = new javax.swing.JPanel();
        pnlNorte = new javax.swing.JPanel();
        pnlSur = new javax.swing.JPanel();
        pnlCentro = new javax.swing.JPanel();
        pnlCNorte = new javax.swing.JPanel();
        pnlCNOeste = new javax.swing.JPanel();
        pnlCNEste = new javax.swing.JPanel();
        pnlCNCentro = new javax.swing.JPanel();
        pnlCOeste = new javax.swing.JPanel();
        pnlCCentro = new javax.swing.JPanel();
        pnlCCNorte = new javax.swing.JPanel();
        pnlCCNNorte = new javax.swing.JPanel();
        pnlCCOeste = new javax.swing.JPanel();
        pnlCCEste = new javax.swing.JPanel();
        pnlCCSur = new javax.swing.JPanel();
        pnlCCSSur = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEste.setBackground(new java.awt.Color(51, 51, 255));
        pnlEste.setPreferredSize(new java.awt.Dimension(60, 0));
        pnlEste.setLayout(new java.awt.BorderLayout());

        pnlESur.setBackground(new java.awt.Color(204, 255, 204));
        pnlESur.setPreferredSize(new java.awt.Dimension(0, 40));

        javax.swing.GroupLayout pnlESurLayout = new javax.swing.GroupLayout(pnlESur);
        pnlESur.setLayout(pnlESurLayout);
        pnlESurLayout.setHorizontalGroup(
            pnlESurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        pnlESurLayout.setVerticalGroup(
            pnlESurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlEste.add(pnlESur, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlEste, java.awt.BorderLayout.EAST);

        pnlOeste.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout pnlOesteLayout = new javax.swing.GroupLayout(pnlOeste);
        pnlOeste.setLayout(pnlOesteLayout);
        pnlOesteLayout.setHorizontalGroup(
            pnlOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlOesteLayout.setVerticalGroup(
            pnlOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(pnlOeste, java.awt.BorderLayout.WEST);

        pnlNorte.setBackground(new java.awt.Color(255, 0, 0));
        pnlNorte.setPreferredSize(new java.awt.Dimension(0, 45));

        javax.swing.GroupLayout pnlNorteLayout = new javax.swing.GroupLayout(pnlNorte);
        pnlNorte.setLayout(pnlNorteLayout);
        pnlNorteLayout.setHorizontalGroup(
            pnlNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        pnlNorteLayout.setVerticalGroup(
            pnlNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        getContentPane().add(pnlNorte, java.awt.BorderLayout.NORTH);

        pnlSur.setBackground(new java.awt.Color(102, 102, 255));
        pnlSur.setPreferredSize(new java.awt.Dimension(0, 30));

        javax.swing.GroupLayout pnlSurLayout = new javax.swing.GroupLayout(pnlSur);
        pnlSur.setLayout(pnlSurLayout);
        pnlSurLayout.setHorizontalGroup(
            pnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        pnlSurLayout.setVerticalGroup(
            pnlSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pnlCentro.setBackground(new java.awt.Color(255, 51, 102));
        pnlCentro.setLayout(new java.awt.BorderLayout());

        pnlCNorte.setBackground(new java.awt.Color(0, 51, 51));
        pnlCNorte.setPreferredSize(new java.awt.Dimension(0, 20));
        pnlCNorte.setLayout(new java.awt.BorderLayout());

        pnlCNOeste.setBackground(new java.awt.Color(102, 255, 255));
        pnlCNOeste.setPreferredSize(new java.awt.Dimension(20, 0));

        javax.swing.GroupLayout pnlCNOesteLayout = new javax.swing.GroupLayout(pnlCNOeste);
        pnlCNOeste.setLayout(pnlCNOesteLayout);
        pnlCNOesteLayout.setHorizontalGroup(
            pnlCNOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnlCNOesteLayout.setVerticalGroup(
            pnlCNOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlCNorte.add(pnlCNOeste, java.awt.BorderLayout.WEST);

        pnlCNEste.setBackground(new java.awt.Color(0, 102, 102));
        pnlCNEste.setPreferredSize(new java.awt.Dimension(20, 0));

        javax.swing.GroupLayout pnlCNEsteLayout = new javax.swing.GroupLayout(pnlCNEste);
        pnlCNEste.setLayout(pnlCNEsteLayout);
        pnlCNEsteLayout.setHorizontalGroup(
            pnlCNEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        pnlCNEsteLayout.setVerticalGroup(
            pnlCNEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlCNorte.add(pnlCNEste, java.awt.BorderLayout.EAST);

        pnlCNCentro.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout pnlCNCentroLayout = new javax.swing.GroupLayout(pnlCNCentro);
        pnlCNCentro.setLayout(pnlCNCentroLayout);
        pnlCNCentroLayout.setHorizontalGroup(
            pnlCNCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        pnlCNCentroLayout.setVerticalGroup(
            pnlCNCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlCNorte.add(pnlCNCentro, java.awt.BorderLayout.CENTER);

        pnlCentro.add(pnlCNorte, java.awt.BorderLayout.NORTH);

        pnlCOeste.setBackground(new java.awt.Color(153, 153, 0));
        pnlCOeste.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout pnlCOesteLayout = new javax.swing.GroupLayout(pnlCOeste);
        pnlCOeste.setLayout(pnlCOesteLayout);
        pnlCOesteLayout.setHorizontalGroup(
            pnlCOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlCOesteLayout.setVerticalGroup(
            pnlCOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCentro.add(pnlCOeste, java.awt.BorderLayout.WEST);

        pnlCCentro.setBackground(new java.awt.Color(255, 0, 51));
        pnlCCentro.setLayout(new java.awt.BorderLayout());

        pnlCCNorte.setBackground(new java.awt.Color(204, 204, 0));
        pnlCCNorte.setPreferredSize(new java.awt.Dimension(0, 70));
        pnlCCNorte.setLayout(new java.awt.BorderLayout());

        pnlCCNNorte.setBackground(new java.awt.Color(102, 0, 0));
        pnlCCNNorte.setPreferredSize(new java.awt.Dimension(0, 20));

        javax.swing.GroupLayout pnlCCNNorteLayout = new javax.swing.GroupLayout(pnlCCNNorte);
        pnlCCNNorte.setLayout(pnlCCNNorteLayout);
        pnlCCNNorteLayout.setHorizontalGroup(
            pnlCCNNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlCCNNorteLayout.setVerticalGroup(
            pnlCCNNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlCCNorte.add(pnlCCNNorte, java.awt.BorderLayout.NORTH);

        pnlCCentro.add(pnlCCNorte, java.awt.BorderLayout.NORTH);

        pnlCCOeste.setBackground(new java.awt.Color(204, 204, 204));
        pnlCCOeste.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout pnlCCOesteLayout = new javax.swing.GroupLayout(pnlCCOeste);
        pnlCCOeste.setLayout(pnlCCOesteLayout);
        pnlCCOesteLayout.setHorizontalGroup(
            pnlCCOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlCCOesteLayout.setVerticalGroup(
            pnlCCOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCCentro.add(pnlCCOeste, java.awt.BorderLayout.WEST);

        pnlCCEste.setBackground(new java.awt.Color(204, 204, 204));
        pnlCCEste.setPreferredSize(new java.awt.Dimension(50, 0));

        javax.swing.GroupLayout pnlCCEsteLayout = new javax.swing.GroupLayout(pnlCCEste);
        pnlCCEste.setLayout(pnlCCEsteLayout);
        pnlCCEsteLayout.setHorizontalGroup(
            pnlCCEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnlCCEsteLayout.setVerticalGroup(
            pnlCCEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCCentro.add(pnlCCEste, java.awt.BorderLayout.EAST);

        pnlCCSur.setBackground(new java.awt.Color(153, 153, 255));
        pnlCCSur.setPreferredSize(new java.awt.Dimension(0, 60));
        pnlCCSur.setLayout(new java.awt.BorderLayout());

        pnlCCSSur.setBackground(new java.awt.Color(0, 255, 255));
        pnlCCSSur.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout pnlCCSSurLayout = new javax.swing.GroupLayout(pnlCCSSur);
        pnlCCSSur.setLayout(pnlCCSSurLayout);
        pnlCCSSurLayout.setHorizontalGroup(
            pnlCCSSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        pnlCCSSurLayout.setVerticalGroup(
            pnlCCSSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCCSur.add(pnlCCSSur, java.awt.BorderLayout.SOUTH);

        pnlCCentro.add(pnlCCSur, java.awt.BorderLayout.SOUTH);

        pnlCentro.add(pnlCCentro, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlCCEste;
    private javax.swing.JPanel pnlCCNNorte;
    private javax.swing.JPanel pnlCCNorte;
    private javax.swing.JPanel pnlCCOeste;
    private javax.swing.JPanel pnlCCSSur;
    private javax.swing.JPanel pnlCCSur;
    private javax.swing.JPanel pnlCCentro;
    private javax.swing.JPanel pnlCNCentro;
    private javax.swing.JPanel pnlCNEste;
    private javax.swing.JPanel pnlCNOeste;
    private javax.swing.JPanel pnlCNorte;
    private javax.swing.JPanel pnlCOeste;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlESur;
    private javax.swing.JPanel pnlEste;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlOeste;
    private javax.swing.JPanel pnlSur;
    // End of variables declaration//GEN-END:variables
}
