/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ivangq
 */
public class Pantalla extends javax.swing.JFrame {
        ArrayList<String> listaProfesiones;
        ArrayList<String> listaProvincias;
        ArrayList<Trabajador> listaTrabajador;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        modeloTabla = (DefaultTableModel) tblTraballadoresDisponibles.getModel();
        modeloCombo = (DefaultComboBoxModel) cBProvincia.getModel();
        //modeloLista = (DefaultListModel) listProfesiones.getModel();
        listaProfesiones = new ArrayList();
        listaProvincias = new ArrayList();
        listaTrabajador = new ArrayList();
        listaProvincias.add("LUGO");
        listaProvincias.add("A CORUÑA");
        listaProvincias.add("PONTEVEDRA");
        listaProvincias.add("OURENSE");
        actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInformacionUsuario = new javax.swing.JPanel();
        lblDNI = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        pnlProvinciaUsuario = new javax.swing.JPanel();
        btnEliminarProvincia = new javax.swing.JButton();
        btnEngadirProvincia = new javax.swing.JButton();
        cBProvincia = new javax.swing.JComboBox<>();
        txtProvincia = new javax.swing.JTextField();
        pnlProfesionUsuario = new javax.swing.JPanel();
        txtProfesion = new javax.swing.JTextField();
        btnEngadirProfesion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProfesiones = new javax.swing.JList<>();
        btnEliminarProfesion = new javax.swing.JButton();
        btnEngadir = new javax.swing.JButton();
        pnlTraballadoresDisponibles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTraballadoresDisponibles = new javax.swing.JTable();
        btnEliminarTraballador = new javax.swing.JButton();
        pnlDetalleTraballador = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDetalle = new javax.swing.JTextArea();
        btnPecharAplicacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlInformacionUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lblDNI.setText("DNI");

        lblNombre.setText("Nombre");

        lblApellido1.setText("Apellido 1");

        lblApellido2.setText("Apellido 2");

        javax.swing.GroupLayout pnlInformacionUsuarioLayout = new javax.swing.GroupLayout(pnlInformacionUsuario);
        pnlInformacionUsuario.setLayout(pnlInformacionUsuarioLayout);
        pnlInformacionUsuarioLayout.setHorizontalGroup(
            pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDNI)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido1)
                    .addComponent(lblApellido2))
                .addGap(20, 20, 20)
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDNI)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido1)
                    .addComponent(txtApellido2))
                .addContainerGap())
        );
        pnlInformacionUsuarioLayout.setVerticalGroup(
            pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido1)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido2)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProvinciaUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Provincia de traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        btnEliminarProvincia.setText("Eliminar Provincia");
        btnEliminarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProvinciaActionPerformed(evt);
            }
        });

        btnEngadirProvincia.setText("Engadir Provincia");
        btnEngadirProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirProvinciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProvinciaUsuarioLayout = new javax.swing.GroupLayout(pnlProvinciaUsuario);
        pnlProvinciaUsuario.setLayout(pnlProvinciaUsuarioLayout);
        pnlProvinciaUsuarioLayout.setHorizontalGroup(
            pnlProvinciaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProvinciaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProvinciaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cBProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProvinciaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEngadirProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProvinciaUsuarioLayout.setVerticalGroup(
            pnlProvinciaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProvinciaUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProvinciaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarProvincia)
                    .addComponent(cBProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProvinciaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEngadirProvincia)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnlProfesionUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profesión do traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        btnEngadirProfesion.setText("Engadir Profesion");
        btnEngadirProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirProfesionActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listProfesiones);

        btnEliminarProfesion.setText("Eliminar Profesion");
        btnEliminarProfesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProfesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProfesionUsuarioLayout = new javax.swing.GroupLayout(pnlProfesionUsuario);
        pnlProfesionUsuario.setLayout(pnlProfesionUsuarioLayout);
        pnlProfesionUsuarioLayout.setHorizontalGroup(
            pnlProfesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfesionUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProfesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(txtProfesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProfesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEngadirProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProfesionUsuarioLayout.setVerticalGroup(
            pnlProfesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfesionUsuarioLayout.createSequentialGroup()
                .addGroup(pnlProfesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProfesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlProfesionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEngadirProfesion))
                .addContainerGap())
        );

        btnEngadir.setText("Engadir traballador");
        btnEngadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirActionPerformed(evt);
            }
        });

        pnlTraballadoresDisponibles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Traballadores Disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        tblTraballadoresDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Provincia", "Profesion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTraballadoresDisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraballadoresDisponiblesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTraballadoresDisponibles);

        javax.swing.GroupLayout pnlTraballadoresDisponiblesLayout = new javax.swing.GroupLayout(pnlTraballadoresDisponibles);
        pnlTraballadoresDisponibles.setLayout(pnlTraballadoresDisponiblesLayout);
        pnlTraballadoresDisponiblesLayout.setHorizontalGroup(
            pnlTraballadoresDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlTraballadoresDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTraballadoresDisponiblesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlTraballadoresDisponiblesLayout.setVerticalGroup(
            pnlTraballadoresDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
            .addGroup(pnlTraballadoresDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTraballadoresDisponiblesLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        btnEliminarTraballador.setText("Eliminar Traballador");
        btnEliminarTraballador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTraballadorActionPerformed(evt);
            }
        });

        pnlDetalleTraballador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Detalle do traballador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        txtAreaDetalle.setColumns(20);
        txtAreaDetalle.setRows(5);
        jScrollPane3.setViewportView(txtAreaDetalle);

        javax.swing.GroupLayout pnlDetalleTraballadorLayout = new javax.swing.GroupLayout(pnlDetalleTraballador);
        pnlDetalleTraballador.setLayout(pnlDetalleTraballadorLayout);
        pnlDetalleTraballadorLayout.setHorizontalGroup(
            pnlDetalleTraballadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleTraballadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDetalleTraballadorLayout.setVerticalGroup(
            pnlDetalleTraballadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalleTraballadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        btnPecharAplicacion.setText("Pechar Aplicacion");
        btnPecharAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPecharAplicacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlInformacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProvinciaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEngadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProfesionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTraballadoresDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarTraballador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDetalleTraballador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPecharAplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlInformacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlProvinciaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlProfesionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTraballadoresDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarTraballador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDetalleTraballador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEngadir)
                    .addComponent(btnPecharAplicacion))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEngadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirActionPerformed
        // TODO add your handling code here:

        boolean correcto = completo();
        if(correcto){
            Trabajador t = new Trabajador();
            t.setDNI(txtDNI.getText().toUpperCase());
            t.setNombre(txtNombre.getText().toUpperCase());
            t.setAp1(txtApellido1.getText().toUpperCase());
            t.setAp2(txtApellido2.getText().toUpperCase());
            t.setProf(listaProfesiones.get(listProfesiones.getSelectedIndex()).toUpperCase());
            t.setProv(listaProvincias.get(cBProvincia.getSelectedIndex()).toUpperCase());
            if(existe(t)){
                return;
            }
            listaTrabajador.add(t);
            actualizar();
            int nfilas =modeloTabla.getRowCount();
            modeloTabla.setRowCount(nfilas+1);
            modeloTabla.setValueAt(t, modeloTabla.getRowCount()-1,0);
            modeloTabla.setValueAt(t.getProv(), modeloTabla.getRowCount()-1,1);
            modeloTabla.setValueAt(t.getProf(), modeloTabla.getRowCount()-1,2);
            
        }
        else{
            return;
        }
        
        
        
        
        
    }//GEN-LAST:event_btnEngadirActionPerformed

    private void btnEliminarTraballadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTraballadorActionPerformed
        // TODO add your handling code here:
        int filaS = tblTraballadoresDisponibles.getSelectedRow();
        if (filaS==-1){
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
            return;
        }
        modeloTabla.removeRow(filaS);
        listaTrabajador.remove(filaS);
        actualizar();
        txtAreaDetalle.setText("");
    }//GEN-LAST:event_btnEliminarTraballadorActionPerformed

    private void btnEliminarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProvinciaActionPerformed
        // TODO add your handling code here:
        if(cBProvincia.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "No ha seleccionado");
            return;
        }
        listaProvincias.remove(cBProvincia.getSelectedIndex());
        actualizar();
    }//GEN-LAST:event_btnEliminarProvinciaActionPerformed

    private void btnEliminarProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProfesionActionPerformed
        // TODO add your handling code here:
        if(listaProfesiones.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay elementos");
            return;
        }
        if(listProfesiones.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "No ha seleccionado");
            return;
        }
        listaProfesiones.remove(listProfesiones.getSelectedIndex());
        actualizar();
    }//GEN-LAST:event_btnEliminarProfesionActionPerformed

    private void btnEngadirProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirProvinciaActionPerformed
        // TODO add your handling code here:
        String provincia = txtProvincia.getText().toUpperCase();
        if(listaProvincias.contains(provincia)){
            JOptionPane.showMessageDialog(this, "La provinica ya existe");
            return;
        }
        listaProvincias.add(provincia);
        actualizar();
    }//GEN-LAST:event_btnEngadirProvinciaActionPerformed

    private void btnEngadirProfesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirProfesionActionPerformed
        // TODO add your handling code here:
        String profesion = txtProfesion.getText().toUpperCase();
        if(listaProfesiones.contains(profesion)){
            JOptionPane.showMessageDialog(this, "La profesion ya existe");
            return;
        }
        listaProfesiones.add(profesion);
        actualizar();
    }//GEN-LAST:event_btnEngadirProfesionActionPerformed

    private void tblTraballadoresDisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraballadoresDisponiblesMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            Trabajador t = listaTrabajador.get(tblTraballadoresDisponibles.getSelectedRow());
            String provincia = t.getProv();
            obtenerTrabajadores(provincia);
            
            
            
        }else{
            Trabajador t = listaTrabajador.get(tblTraballadoresDisponibles.getSelectedRow());
            txtAreaDetalle.setText("DATOS DO TRABALLADOR \n"
                    +"DNI: "+t.getDNI()+"\n"
                    +"NOME: "+t.getNombre()+"\n"
                    +"APELIDO 1: "+t.getAp1()+"\n"
                    +"APELIDO 2: "+t.getAp2()+"\n"
                    +"PROVINCIA: "+t.getProv()+"\n"
                    +"PROFESION: "+t.getProf()+"\n"
                            );
        }
    }//GEN-LAST:event_tblTraballadoresDisponiblesMouseClicked

    private void btnPecharAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPecharAplicacionActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_btnPecharAplicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarProfesion;
    private javax.swing.JButton btnEliminarProvincia;
    private javax.swing.JButton btnEliminarTraballador;
    private javax.swing.JButton btnEngadir;
    private javax.swing.JButton btnEngadirProfesion;
    private javax.swing.JButton btnEngadirProvincia;
    private javax.swing.JButton btnPecharAplicacion;
    private javax.swing.JComboBox<String> cBProvincia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> listProfesiones;
    private javax.swing.JPanel pnlDetalleTraballador;
    private javax.swing.JPanel pnlInformacionUsuario;
    private javax.swing.JPanel pnlProfesionUsuario;
    private javax.swing.JPanel pnlProvinciaUsuario;
    private javax.swing.JPanel pnlTraballadoresDisponibles;
    private javax.swing.JTable tblTraballadoresDisponibles;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextArea txtAreaDetalle;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProfesion;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    private DefaultListModel modeloLista = new DefaultListModel();
    
    
    
    public boolean isEmpty(JTextField txt){
        
        if (txt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Faltan campos por completar");
            return true;
        }
        return false;
    }
    
    public boolean completo(){
        if(!isEmpty(txtDNI)){
            if(!isEmpty(txtNombre)){
                if(!isEmpty(txtApellido1)){
                    if(!isEmpty(txtApellido2)){
                        if((listProfesiones.getSelectedIndex()!=-1)){
                            if((cBProvincia.getSelectedIndex()!=-1)){
                                return true;
                            }
                            else{
                                JOptionPane.showMessageDialog(this, "Selecciona una Provincia");
                            }
                        }else{
                                JOptionPane.showMessageDialog(this, "Selecciona una Profesion");
                        }
                    }
                }
            }
        }
        return false;
    }
    
    public void actualizarCombo(){
        DefaultComboBoxModel nuevo = new DefaultComboBoxModel();
        for (String objeto : listaProvincias) {
            nuevo.addElement(objeto);
        }
        cBProvincia.setModel(nuevo);

    }
    
    public void actualizarLista(){
        DefaultListModel nuevo = new DefaultListModel();
        for (String objeto : listaProfesiones) {
            nuevo.addElement(objeto);
        }
        listProfesiones.setModel(nuevo);
    }
    
    
    public void actualizarTabla(){
        DefaultTableModel nuevo = new DefaultTableModel();
        for (Trabajador t : listaTrabajador) {
            int nfilas =nuevo.getRowCount();
            nuevo.setRowCount(nfilas+1);
            nuevo.setValueAt(t.getNombre(), nuevo.getRowCount()-1,0);
            nuevo.setValueAt(t.getProv(), nuevo.getRowCount()-1,1);
            nuevo.setValueAt(t.getProf(), nuevo.getRowCount()-1,2);
        }
        tblTraballadoresDisponibles.setModel(nuevo);
    }
    
    
    public void actualizar(){
      actualizarCombo();
      actualizarLista();
      //actualizarTabla();
    }
    
    public boolean existe (Trabajador t){
        for (Trabajador trabajador : listaTrabajador) {
            if(trabajador.getDNI().equals(t.getDNI())){
                JOptionPane.showMessageDialog(this, "El usuario ya existe");
                return true;
            }
        }
    
        return false;
    }
    
    public void obtenerTrabajadores( String provincia){
        StringBuilder aux = new StringBuilder("");
        int contador = 0;
        for (Trabajador t : listaTrabajador) {
            if(t.getProv().equals(provincia)){
                aux.append(t.toString()+"\n");
                contador++;
            }
        }
        JOptionPane.showMessageDialog(this,"Traballadores de "+provincia+" : "+contador+"\n"+aux);

    }

}
