/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio2;

import javax.swing.JOptionPane;

/**
 *
 * @author ivangq
 */
public class Pantalla extends javax.swing.JFrame {
    ListaProvincias lista = new ListaProvincias();
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        for (int i=0;i<lista.size();i++) {
            cBProvincias.addItem(lista.getProvincia(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlInformacion = new javax.swing.JPanel();
        cBProvincias = new javax.swing.JComboBox<>();
        cBLocalidades = new javax.swing.JComboBox<>();
        lblLocalidad = new javax.swing.JLabel();
        lblProvincia = new javax.swing.JLabel();
        pnlGestionInformacion = new javax.swing.JPanel();
        btnEjecutar = new javax.swing.JButton();
        rBeliminar = new javax.swing.JRadioButton();
        rBmodificar = new javax.swing.JRadioButton();
        rBnueva = new javax.swing.JRadioButton();
        lblLocalidadTxt = new javax.swing.JLabel();
        txtLocalidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        cBProvincias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cBProvinciasItemStateChanged(evt);
            }
        });
        cBProvincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBProvinciasActionPerformed(evt);
            }
        });

        lblLocalidad.setText("Localidad");

        lblProvincia.setText("Provincia");

        javax.swing.GroupLayout pnlInformacionLayout = new javax.swing.GroupLayout(pnlInformacion);
        pnlInformacion.setLayout(pnlInformacionLayout);
        pnlInformacionLayout.setHorizontalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProvincia)
                    .addComponent(lblLocalidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cBProvincias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cBLocalidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlInformacionLayout.setVerticalGroup(
            pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocalidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlGestionInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        btnEjecutar.setText("EJECUTAR");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBeliminar);
        rBeliminar.setText("Eliminar localidad seleccionada");

        buttonGroup1.add(rBmodificar);
        rBmodificar.setText("Modificar localidad seleccionada");

        buttonGroup1.add(rBnueva);
        rBnueva.setSelected(true);
        rBnueva.setText("Nueva localidad");
        rBnueva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBnuevaItemStateChanged(evt);
            }
        });
        rBnueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBnuevaActionPerformed(evt);
            }
        });

        lblLocalidadTxt.setText("Localidad");

        javax.swing.GroupLayout pnlGestionInformacionLayout = new javax.swing.GroupLayout(pnlGestionInformacion);
        pnlGestionInformacion.setLayout(pnlGestionInformacionLayout);
        pnlGestionInformacionLayout.setHorizontalGroup(
            pnlGestionInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGestionInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGestionInformacionLayout.createSequentialGroup()
                        .addGroup(pnlGestionInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rBeliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rBmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(rBnueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(pnlGestionInformacionLayout.createSequentialGroup()
                        .addComponent(lblLocalidadTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalidad)))
                .addContainerGap())
        );
        pnlGestionInformacionLayout.setVerticalGroup(
            pnlGestionInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGestionInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlGestionInformacionLayout.createSequentialGroup()
                        .addComponent(rBeliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBmodificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBnueva))
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlGestionInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidadTxt)
                    .addComponent(txtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGestionInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlGestionInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cBProvinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBProvinciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBProvinciasActionPerformed

    private void cBProvinciasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cBProvinciasItemStateChanged
        // TODO add your handling code here:
        actualizarLocalidades();
    }//GEN-LAST:event_cBProvinciasItemStateChanged

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        // TODO add your handling code here:
        
        if(rBnueva.isSelected()){
            String nombreL = txtLocalidad.getText();
            String nombreP =cBProvincias.getSelectedItem().toString();
            Provincia p = lista.getProvincia(nombreP);
            Localidad localidad = new Localidad(nombreL);
            p.getListaLocalidades().add(localidad);
            actualizarLocalidades();
        
        }
        else if(rBeliminar.isSelected()){
            //NO FUNCIONA
            String nombreL = cBLocalidades.getSelectedItem().toString();
            String nombreP =cBProvincias.getSelectedItem().toString();
            Provincia p = lista.getProvincia(nombreP);
            Localidad l = p.getLocalidad(nombreL);
            lista.removeLocalidad(p, l);
            actualizarLocalidades();
        }
        
        else{//MODIFICAR NO IMPLEMENTADO TODAVIA
        
        }
    
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void rBnuevaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBnuevaItemStateChanged
        // TODO add your handling code here:
        txtLocalidad.setEnabled(false);
    }//GEN-LAST:event_rBnuevaItemStateChanged

    private void rBnuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBnuevaActionPerformed
        // TODO add your handling code here:
        txtLocalidad.setEnabled(true);
    }//GEN-LAST:event_rBnuevaActionPerformed
    
    public void actualizarLocalidades(){
        String nombreProvinicia = cBProvincias.getSelectedItem().toString();
        Provincia p = lista.getProvincia(nombreProvinicia);
        cBLocalidades.removeAllItems();
        for (int i=0;i<p.getListaLocalidades().size();i++){
            cBLocalidades.addItem(p.getListaLocalidades().get(i).getNombre());
        }
        
    
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cBLocalidades;
    private javax.swing.JComboBox<String> cBProvincias;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblLocalidadTxt;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JPanel pnlGestionInformacion;
    private javax.swing.JPanel pnlInformacion;
    private javax.swing.JRadioButton rBeliminar;
    private javax.swing.JRadioButton rBmodificar;
    private javax.swing.JRadioButton rBnueva;
    private javax.swing.JTextField txtLocalidad;
    // End of variables declaration//GEN-END:variables
}
